disable_existing_loggers: false
formatters:
  detailed:
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s'
  simple:
    format: '%(levelname)s - %(message)s'
  standard:
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console_handler:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG
    stream: ext://sys.stdout
  error_file_handler:
    backupCount: 3
    class: logging.handlers.RotatingFileHandler
    encoding: utf8
    filename: ~/Library/Logs/Nexy/errors.log
    formatter: detailed
    level: ERROR
    maxBytes: 5242880
  file_handler:
    backupCount: 5
    class: logging.handlers.RotatingFileHandler
    encoding: utf8
    filename: ~/Library/Logs/Nexy/app.log
    formatter: detailed
    level: DEBUG
    maxBytes: 10485760
loggers:
  Nexy:
    handlers:
    - file_handler
    - console_handler
    - error_file_handler
    level: DEBUG
    propagate: false
  nexy.accessibility:
    handlers:
    - file_handler
    - console_handler
    level: DEBUG
    propagate: false
  nexy.audio:
    handlers:
    - file_handler
    level: DEBUG
    propagate: false
  nexy.grpc:
    handlers:
    - file_handler
    level: DEBUG
    propagate: false
  nexy.screen_capture:
    handlers:
    - file_handler
    level: DEBUG
    propagate: false
  nexy.stt:
    handlers:
    - file_handler
    level: DEBUG
    propagate: false
root:
  handlers:
  - system_handler
  level: WARNING
version: 1
